name: Publish SGAC

on:
  push:
    branches: [main]

jobs:
  create-docker-image-on-self-hosted-arm64:
    runs-on: self-hosted
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.SGAC_DEPLOY_TOKEN }}
      
      - name: Build the SGAC Docker image
        run: |
          docker build . -t ghcr.io/chemacli/sgac-js:latest
          docker push ghcr.io/chemacli/sgac-js:latest

  deploy:
    needs: create-docker-image-on-self-hosted-arm64
    runs-on: ubuntu-latest
    steps:
    - name: Generate SSH key
        run: |
          ssh-keygen -t rsa -b 4096 -C "github-action" -f ~/.ssh/id_rsa -N ""
          echo "SSH_PRIVATE_KEY=$(cat ~/.ssh/id_rsa)" >> $GITHUB_ENV
          echo "SSH_PUBLIC_KEY=$(cat ~/.ssh/id_rsa.pub)" >> $GITHUB_ENV

    - name: Add SSH Key to GitHub Secrets
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SGAC_SSH_IP }}
          username: ${{ secrets.SGAC_SSH_USER }}
          password: ${{ secrets.SGAC_SSH_PASSWORD }}
          port: 22
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "${{ secrets.SSH_PRIVATE_KEY }}" >> ~/.ssh/authorized_keys
            whoami
            cd ~/sgacjs
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.SGAC_DEPLOY_TOKEN }}
            docker pull ghcr.io/chemacli/sgac-js:latest
            docker stop sgac-js && docker rm sgac-js
            docker run -d \
              --name sgac-js \
              -p 4321:4321 \
              -w /app \
              --restart always \
              ghcr.io/chemacli/sgac-js:latest
            
            
            
            
      
