name: Publish SGAC

on:
  push:
    branches: [main]

jobs:
  create-docker-image-on-self-hosted-arm64:
    runs-on: self-hosted
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.SGAC_DEPLOY_TOKEN }}
      
      - name: Build the SGAC Docker image
        run: |
          docker build . -t ghcr.io/chemacli/sgac-js:latest
          docker push ghcr.io/chemacli/sgac-js:latest

  deploy:
    needs: create-docker-image-on-self-hosted-arm64
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SGAC_SSH_IP }}
          username: ${{ secrets.SGAC_SSH_USER }}
          password: ${{ secrets.SGAC_SSH_PASSWORD }}
          port: 22
          script: |
            whoami
            cd ~/sgacjs
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.SGAC_DEPLOY_TOKEN }}
            docker pull ghcr.io/chemacli/sgac-js:latest
            docker stop sgac-js && docker rm sgac-js
            docker run -d \
              --name sgac-js \
              -p 4321:4321 \
              -w /app \
              --restart always \
              ghcr.io/chemacli/sgac-js:latest
            
            
            
            
      
